package com.svllvsx.notifyrelay.ui

import com.svllvsx.notifyrelay.domain.model.AppLanguage
import java.util.Locale

data class UiStrings(
    val dashboard: String,
    val apps: String,
    val settings: String,
    val diagnostics: String,
    val appTitle: String,
    val appSubtitle: String,
    val phone: String,
    val serverAddress: String,
    val serverExample: String,
    val pasteUrl: String,
    val checkServer: String,
    val serverOk: String,
    val pairingCode: String,
    val pairingHint: String,
    val linkDevice: String,
    val linkedOk: String,
    val linkFailed: String,
    val setupStatus: String,
    val notificationAccess: String,
    val smsAccess: String,
    val tokenNote: String,
    val relayTitle: String,
    val relaySubtitle: String,
    val online: String,
    val issue: String,
    val deviceLinked: String,
    val eventsViaServer: String,
    val lastSync: String,
    val never: String,
    val eventQueue: String,
    val pending: String,
    val failed: String,
    val status: String,
    val ok: String,
    val error: String,
    val appsTitle: String,
    val appsSubtitle: String,
    val searchApp: String,
    val showSystemApps: String,
    val noApps: String,
    val noAppsDesc: String,
    val settingsTitle: String,
    val settingsSubtitle: String,
    val server: String,
    val notSet: String,
    val setupAgain: String,
    val forwarding: String,
    val notifications: String,
    val sms: String,
    val permissions: String,
    val privacy: String,
    val resetDevice: String,
    val language: String,
    val systemLanguage: String,
    val russian: String,
    val english: String,
    val fullText: String,
    val masked: String,
    val minimal: String,
    val fullTextDesc: String,
    val maskedDesc: String,
    val minimalDesc: String,
    val diagnosticsTitle: String,
    val diagnosticsSubtitle: String,
    val enabled: String,
    val noAccess: String,
    val allowed: String,
    val lastError: String,
    val noErrors: String,
    val testMessage: String,
    val testNotSent: String,
    val testAccepted: String,
    val testFailed: String,
    val sendTest: String,
    val open: String,
    val done: String,
    val required: String,
    val smsHelpTitle: String,
    val smsHelpText: String,
    val openAppInfo: String,
    val requestSms: String,
)

fun AppLanguage.resolveLanguage(): AppLanguage = when (this) {
    AppLanguage.RU, AppLanguage.EN -> this
    AppLanguage.SYSTEM -> if (Locale.getDefault().language.equals("ru", ignoreCase = true)) AppLanguage.RU else AppLanguage.EN
}

fun strings(language: AppLanguage): UiStrings = if (language.resolveLanguage() == AppLanguage.RU) ruStrings else enStrings

private val ruStrings = UiStrings(
    dashboard = "Главная", apps = "Приложения", settings = "Настройки", diagnostics = "Проверка",
    appTitle = "Notify Relay", appSubtitle = "Пересылайте уведомления и SMS в Telegram через свой сервер.", phone = "Телефон",
    serverAddress = "Адрес сервера", serverExample = "Например: https://example.trycloudflare.com", pasteUrl = "Вставить URL из буфера", checkServer = "Проверить сервер", serverOk = "Сервер доступен. Теперь можно привязать устройство.",
    pairingCode = "Код привязки", pairingHint = "Введите 6 цифр из сообщения бота", linkDevice = "Привязать устройство", linkedOk = "Устройство привязано. Откройте разрешения и выберите приложения.", linkFailed = "Не удалось привязать устройство. Проверьте код.", setupStatus = "Статус настройки",
    notificationAccess = "Доступ к уведомлениям", smsAccess = "Доступ к SMS", tokenNote = "Токен Telegram-бота хранится только на сервере. Android отправляет события только на ваш сервер.",
    relayTitle = "Ретрансляция", relaySubtitle = "Уведомления и SMS через ваш сервер", online = "В сети", issue = "Проблема", deviceLinked = "Устройство привязано", eventsViaServer = "События отправляются через сервер.", lastSync = "Последняя синхронизация", never = "нет",
    eventQueue = "Очередь событий", pending = "Ожидают", failed = "Ошибки", status = "Статус", ok = "ОК", error = "Ошибка",
    appsTitle = "Приложения", appsSubtitle = "Выберите, какие уведомления пересылать", searchApp = "Поиск приложения", showSystemApps = "Показывать системные приложения", noApps = "Приложения не найдены", noAppsDesc = "Android не вернул список установленных приложений. Проверьте установку APK и перезапустите приложение.",
    settingsTitle = "Настройки", settingsSubtitle = "Сервер, пересылка, приватность и устройство", server = "Сервер", notSet = "Не задан", setupAgain = "Настроить сервер заново", forwarding = "Пересылка", notifications = "Уведомления", sms = "SMS", permissions = "Разрешения", privacy = "Приватность", resetDevice = "Сбросить привязку устройства", language = "Язык", systemLanguage = "Как в системе", russian = "Русский", english = "English",
    fullText = "Полный текст", masked = "Скрывать коды и номера", minimal = "Только факт уведомления", fullTextDesc = "Отправляет содержимое уведомлений и SMS без маскировки.", maskedDesc = "Оставляет имя контакта/чат, но скрывает коды, телефоны, карты и email в тексте.", minimalDesc = "Отправляет только факт события без текста сообщения.",
    diagnosticsTitle = "Диагностика", diagnosticsSubtitle = "Проверка системных условий", enabled = "Включено", noAccess = "Нет доступа", allowed = "Разрешено", lastError = "Последняя ошибка", noErrors = "Ошибок нет", testMessage = "Тестовое сообщение", testNotSent = "Тестовое сообщение ещё не отправлялось", testAccepted = "Сервер принял тестовое сообщение.", testFailed = "Не удалось отправить тестовое сообщение.", sendTest = "Отправить тест", open = "Открыть", done = "Готово", required = "Требуется доступ",
    smsHelpTitle = "Разрешение SMS", smsHelpText = "Если Android считает приложение установленным из неизвестного источника, откройте экран \"О приложении\", нажмите три точки справа сверху и выберите \"Разрешить ограниченные настройки\". После этого вернитесь и выдайте доступ к SMS.", openAppInfo = "Открыть о приложении", requestSms = "Запросить SMS",
)

private val enStrings = UiStrings(
    dashboard = "Home", apps = "Apps", settings = "Settings", diagnostics = "Check",
    appTitle = "Notify Relay", appSubtitle = "Forward notifications and SMS to Telegram through your own server.", phone = "Phone",
    serverAddress = "Server URL", serverExample = "Example: https://example.trycloudflare.com", pasteUrl = "Paste URL from clipboard", checkServer = "Check server", serverOk = "Server is reachable. You can link the device now.",
    pairingCode = "Pairing code", pairingHint = "Enter 6 digits from the bot message", linkDevice = "Link device", linkedOk = "Device linked. Open permissions and select apps.", linkFailed = "Failed to link device. Check the code.", setupStatus = "Setup status",
    notificationAccess = "Notification access", smsAccess = "SMS access", tokenNote = "Telegram bot token is stored only on the server. Android sends events only to your server.",
    relayTitle = "Relay", relaySubtitle = "Notifications and SMS through your server", online = "Online", issue = "Issue", deviceLinked = "Device linked", eventsViaServer = "Events are sent through the server.", lastSync = "Last sync", never = "never",
    eventQueue = "Event queue", pending = "Pending", failed = "Failed", status = "Status", ok = "OK", error = "Error",
    appsTitle = "Apps", appsSubtitle = "Choose which notifications to forward", searchApp = "Search app", showSystemApps = "Show system apps", noApps = "No apps found", noAppsDesc = "Android did not return installed apps. Check APK installation and restart the app.",
    settingsTitle = "Settings", settingsSubtitle = "Server, forwarding, privacy and device", server = "Server", notSet = "Not set", setupAgain = "Set up server again", forwarding = "Forwarding", notifications = "Notifications", sms = "SMS", permissions = "Permissions", privacy = "Privacy", resetDevice = "Reset device link", language = "Language", systemLanguage = "System default", russian = "Русский", english = "English",
    fullText = "Full text", masked = "Hide codes and numbers", minimal = "Event only", fullTextDesc = "Sends notification and SMS content without masking.", maskedDesc = "Keeps contact/chat name, but hides codes, phones, cards and emails in message text.", minimalDesc = "Sends only the event fact without message text.",
    diagnosticsTitle = "Diagnostics", diagnosticsSubtitle = "System conditions check", enabled = "Enabled", noAccess = "No access", allowed = "Allowed", lastError = "Last error", noErrors = "No errors", testMessage = "Test message", testNotSent = "Test message was not sent yet", testAccepted = "Server accepted the test message.", testFailed = "Failed to send the test message.", sendTest = "Send test", open = "Open", done = "Done", required = "Access required",
    smsHelpTitle = "SMS permission", smsHelpText = "If Android treats this app as installed from an unknown source, open App info, tap the three dots in the top right, and choose Allow restricted settings. Then return and grant SMS access.", openAppInfo = "Open App info", requestSms = "Request SMS",
)
